### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Erriez** [anthonykawa/artifact-server#3]
Thanks for creating this workaround for issue https://github.com/nektos/act/issues/329. How is this project supposed to work?

I have a `.github/workflows/CI.yaml`:
```yaml
jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache buildx layers
        uses: actions/cache@v2
        with:
          path: /tmp/buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
```

This generates the output:

```
act
...
[CI/Build images] ⭐  Run Cache buildx layers
INFO[0001]   ☁  git clone 'https://github.com/actions/cache' # ref=v2 
[CI/Build images]   🐳  docker cp src=/home/a/.cache/act/actions-cache@v2/ dst=/var/run/act/actions/actions-cache@v2/
[CI/Build images]   🐳  docker exec cmd=[mkdir -p /var/run/act/actions/actions-cache@v2/] user=
[CI/Build images]   🐳  docker exec cmd=[node /var/run/act/actions/actions-cache@v2/dist/restore/index.js] user=
[CI/Build images]   ❓  ::save-state name=CACHE_KEY::Linux-buildx-3a96bf21701334370d6ffda25c4d7c5f6409ddf0
[CI/Build images]   💬  ::debug::Resolved Keys:
[CI/Build images]   💬  ::debug::["Linux-buildx-3a96bf21701334370d6ffda25c4d7c5f6409ddf0","Linux-buildx-"]
[CI/Build images]   💬  ::debug::Checking zstd --version
[CI/Build images]   💬  ::debug::*** zstd command line interface 64-bits v1.4.4, by Yann Collet ***
[CI/Build images]   💬  ::debug::getCacheEntry - Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[CI/Build images]   💬  ::debug::getCacheEntry - Attempt 2 of 2 failed with error: Cache Service Url not found, unable to restore cache.
| [warning]getCacheEntry failed: Cache Service Url not found, unable to restore cache.
[CI/Build images]   ⚙  ::set-output:: cache-hit=false
```

Then I cloned this application:
```bash
git clone https://github.com/anthonykawa/artifact-server.git
cd artifact-server
npm install
npm run start
    ...
    Listening on port 8080
```

I've added the environment variable to the end of `Cache buildx layers` (not sure if this is correct):
```yaml
        env:
          ACTIONS_CACHE_URL: "localhost:8080/"
```

Run again:
```bash
act
...
[CI/Build images]   💬  ::debug::Resource Url: localhost:8080/_apis/artifactcache/cache?keys=Linux-buildx-3a96bf21701334370d6ffda25c4d7c5f6409ddf0%252CLinux-buildx-&version=7db6cb4c78cbac0d95563089572776322af57c580ca11c70393999edb6ca4e4c
[CI/Build images]   💬  ::debug::getCacheEntry - Attempt 1 of 2 failed with error: connect ECONNREFUSED 127.0.0.1:80
[CI/Build images]   💬  ::debug::Resource Url: localhost:8080/_apis/artifactcache/cache?keys=Linux-buildx-3a96bf21701334370d6ffda25c4d7c5f6409ddf0%252CLinux-buildx-&version=7db6cb4c78cbac0d95563089572776322af57c580ca11c70393999edb6ca4e4c
[CI/Build images]   💬  ::debug::getCacheEntry - Attempt 2 of 2 failed with error: connect ECONNREFUSED 127.0.0.1:80
```

It tries to connect, but looks like `/_apis/artifactcache/` is not resolved. Any idea? Thanks!
